function m(c,a,b,d){c.h.ia(c.Y,a,b,d)}function r(c,a,b,d){c.h.m?m(c,a,b,d):c.h.Jb()._OnMessageFromDOM({type:"event",component:c.Y,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.Y,a,b)}function u(c,a){for(const [b,d]of a)t(c,b,d)}window.U=class{constructor(c,a){this.h=c;this.Y=a}Va(){}};window.sc=class{constructor(){}};"use strict";class aa{constructor(c){this.Z=c;this.Ga=!1;this.Ja=!0;this.$=this.A=this.Sa=-1}}
function ba(c,a){const b=a.elementId,d=c.Xa(b,a),e=new aa(d);c.I.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ja=!!a.isVisible;d.addEventListener("focus",()=>{v(c,"elem-focused",b)});d.addEventListener("blur",()=>{v(c,"elem-blurred",b)});const f=a.htmlIndex;e.Sa=f;e.$=a.htmlZIndex;c.L&&(a=c.h.va(f),e.A=a,c.h.ha(a).appendChild(d))}function ca(c,a,b){t(c,a,d=>{const e=w(c,d.elementId);return b(e,d)})}
function w(c,a){c=c.I.get(a);if(!c)throw Error(`no element with id ${a}`);return c.Z}function v(c,a,b,d){d||(d={});d.elementId=b;m(c,a,d)}function da(c,a,b){var d;d||(d={});d.elementId=b;r(c,a,d)}
window.ua=class extends self.U{constructor(c){super(c,"text-input");this.I=new Map;this.L=!0;u(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const b=w(this,a);this.L&&b.parentElement.removeChild(b);this.I.delete(a)}],["set-visible",a=>{if(this.L){var b=this.I.get(a.elementId),d=b.Z;b.Ga?d.style.display=a.isVisible?"":"none":b.Ja=!!a.isVisible}}],["update-position",a=>{if(this.L){var b=this.I.get(a.elementId),d=b.Z,e=this.h;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;b.Sa=f;f=e.va(f);f!==b.A&&(d.remove(),e.ha(f).appendChild(d),b.A=f,e.Da());a=a.htmlZIndex;a!==b.$&&(b.$=a,e.Da());b.Ga||(b.Ga=!0,b.Ja&&(d.style.display=""))}}],["update-state",a=>{const b=w(this,a.elementId);this.wa(b,a)}],["focus",a=>this.Aa(a)],["set-css-style",a=>{const b=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?b.style.setProperty(d,a):b.style[d]=a}],["set-attribute",a=>
{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);ca(this,"get-element",a=>a)}Xa(){throw Error("required override");}wa(){throw Error("required override");}Aa(c){var a=w(this,c.elementId);c.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let fa=0;
function y(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.ic?new Promise(b=>{const d="c3_resolve_"+fa;++fa;self[d]=b;a.textContent=c.mc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function ha(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let z=new Audio;
const ia={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function ja(c){c=await ka(c);return(new TextDecoder("utf-8")).decode(c)}
function ka(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const A=[];let B=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let la=0;const ma=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");ma.push(c)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.C=class c{constructor(a){this.m=a.oc;this.ca=null;this.l="";this.O=a.lc;this.fa={};this.La=this.R=null;this.M=[];this.J=null;this.ob=!0;this.j=[];this.Pa=[];this.Qa=!1;this.qb=()=>this.Hb();this.nb=!1;this.aa=null;this.N=-1;this.dc=()=>this.Sb();this.da=new Set;this.Ta=null;this.rb=[];this.g=a.sb;this.Ia="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);b&&
90<=parseInt(b[1],10)||(this.m=!1)}this.u()?self.chrome.webview.addEventListener("message",b=>this.gb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.gb(b));this.na=this.B=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Wb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Nb());this.i("runtime","cordova-fetch-local-file",b=>this.Ob(b));this.i("runtime","create-job-worker",()=>this.Pb());this.i("runtime","send-wrapper-extension-message",b=>this.Vb(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.ja(a)):this.ja(a)}ub(){return this.j[0].canvas}va(a){return Math.min(a,this.j.length-1)}ha(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].ga}yb(){return ea&&
"cordova"===this.g}W(){const a=navigator.userAgent;return ea&&na.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}wb(){return x}Ya(){return x&&na.has(this.g)}Za(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}u(){return this.Za()||"xbox-uwp-webview2"===this.g}async ja(a){this.m&&!await ha()&&(this.m=!1);"macos-wkwebview"===this.g?this.G({type:"ready"}):this.u()&&(this.Zb(),this.rb=(await this.Mb()).registeredComponentIds);
if("playable-ad"===this.g){this.B=self.c3_base64files;this.na={};await this.Eb();for(let d=0,e=a.S.length;d<e;++d){var b=a.S[d];this.na.hasOwnProperty(b)?a.S[d]={ic:!0,mc:this.na[b]}:this.B.hasOwnProperty(b)&&(a.S[d]=URL.createObjectURL(this.B[b]))}a.ra=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.$a(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.kc?this.l=a.kc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.qc&&(this.fa=a.qc);b=new MessageChannel;this.ca=b.port1;this.ca.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Rb(d));this.aa=new self.zb(this);await pa(this.aa);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Lb(a,b.port2):await this.Kb(a,b.port2)}ya(a){a=this.fa.hasOwnProperty(a)?this.fa[a]:a.endsWith("/workermain.js")&&this.fa.hasOwnProperty("workermain.js")?this.fa["workermain.js"]:"playable-ad"===this.g&&this.B.hasOwnProperty(a)?this.B[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ta(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Ia)return a=await this.sa(d.hc?a:this.O+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}v(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}eb(a){var b=this.l,d=location.href,e=this.v(),f=this.o(),h=window.devicePixelRatio,g=c.V(),k=a.wc,l=window.cr_previewImageBlobs||this.B,n=window.cr_previewProjectFileBlobs,p=window.cr_previewProjectFiles,q=window.cr_swClientId||
"";a=a.sb;var Aa=(new URLSearchParams(self.location.search)).has("debug"),O=this.aa;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:h,isFullscreen:g,projectData:k,previewImageBlobs:l,previewProjectFileBlobs:n,previewProjectFileSWUrls:p,swClientId:q,exportType:a,isDebug:Aa,ife:!!self.vc,jobScheduler:{inputPort:O.Ha,outputPort:O.Oa,maxNumWorkers:O.bc},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.O+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.O+"opus.wasm.wasm",isFileProtocol:this.Ia,isiOSCordova:this.yb(),isiOSWebView:this.W(),isWindowsWebView2:this.Za(),isAnyWebView2Wrapper:this.u(),wrapperComponentIds:this.rb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Lb(a,b){const d=this.ya(a.pc);"preview"===this.g?(this.R=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,n)=>{const p=q=>{this.R.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():n()};this.R.addEventListener("message",
p);this.R.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):this.R=await this.ta(d,this.l,{type:"module",name:"Runtime",hc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,ga:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
let g=a.ra||[],k=a.S;g=await Promise.all(g.map(l=>this.K(l)));k=await Promise.all(k.map(l=>this.K(l)));if("cordova"===this.g)for(let l=0,n=a.qa.length;l<n;++l){const p=a.qa[l],q=p[0];if(q===a.Ua||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.K(q)}this.R.postMessage(Object.assign(this.eb(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.qa,mainProjectScript:a.Ua,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[b,f,...qa(this.aa)]);this.M=D.map(l=>new l(this));this.cb();G(e);H(h);ra(this.J);self.c3_callFunction=(l,n)=>{var p=this.J;return p.h.Ab(p.Y,{name:l,params:n})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.ia("runtime","go-to-last-error-script"))}async Kb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,ga:e});window.c3canvas=d;
self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.M=D.map(g=>new g(this));this.cb();G(d);H(e);e=a.S.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.ra)){var f=[...a.ra].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.K(g)));await Promise.all(e.map(g=>y(g)));e=self.C3_ProjectScriptsStatus;f=a.Ua;const h=a.qa;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.K(k),await y(k),"preview"!==this.g||
e[g]||this.hb(g,"main script did not run to completion")}catch(l){this.hb(g,l)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))k=await this.K(k),await y(k);"preview"===this.g&&"object"!==typeof self.rc.tc?(this.la(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.eb(a),{isInWorker:!1,
messagePort:b,canvas:d,runOnStartupFunctions:ma}),ra(this.J),this.fb(),this.La=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.La,a))}hb(a,b){this.la();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}fb(){this.la()}la(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=
null)}async Pb(){const a=await sa(this.aa);return{outputPort:a,transferables:[a]}}Wb(a){if(!this.nb){var b=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,ga:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.ob&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.ob=
!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,ga:n}=this.j.pop();n.remove();this.m&&!d?this.Pa.push(l):l.remove()}else if(b>this.j.length)for(let l=0,n=b-this.j.length;l<n;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),
d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,G(b),H(d),this.j.push({canvas:b,ga:d});for(const l of this.M)if(l instanceof window.ua&&l.L)for(const n of l.I.values())e=l.h.va(n.Sa),f=n.A,-1!==e&&-1!==f&&e!==f&&(f=n.Z,f.remove(),l.h.ha(e).appendChild(f),n.A=e);this.Da();return{addedCanvases:a,transferables:k}}Nb(){for(const a of this.Pa)a.remove();
this.Pa.length=0}Da(){this.Qa||(this.Qa=!0,this.$a(this.qb))}Hb(){this.Yb(this.qb);this.Qa=!1;let a=[];for(var b of this.M)if(b instanceof window.ua){var d=b.L?[...b.I.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.A,l=g.A;return k!==l?k-l:h.$-g.$});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.A!==b&&(this.bb(b,a.slice(d,e)),b=h.A,d=e)}d<e&&this.bb(b,a.slice(d,e))}bb(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.Z);var d=new Set(b);a=this.ha(a);for(var e=Array.from(a.children).filter(k=>
d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Jb(){if(this.m)throw Error("not available in worker mode");return this.La}ia(a,b,d,e){this.ca.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}Ab(a,b){const d=la++,e=new Promise((f,h)=>{F.set(d,{resolve:f,reject:h})});this.ca.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,
responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===b)return this.Qb(a);if("result"===b)this.Tb(a);else if("runtime-ready"===b)this.Ub();else if("alert-error"===b)this.la(),alert(a.message);else if("creating-runtime"===b)this.fb();else throw Error(`unknown message '${b}'`);}Qb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=E.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ka(f,
!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ka(f,!0,g)).catch(g=>{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ka(f,!1,""+g)}):this.ka(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ka(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.ca.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Tb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=F.get(b);d?e.resolve(a):
e.reject(a);F.delete(b)}i(a,b,d){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static T(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}cb(){for(const a of this.M)if("runtime"===a.Y){this.J=a;return}throw Error("cannot find runtime DOM handler");}Rb(a){this.ia("debugger","message",a)}Ub(){for(const a of this.M)a.Va()}static V(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||oa)}static ma(a){oa=!!a}$a(a){this.da.add(a);this.Ca()}Yb(a){this.da.delete(a);0===this.da.size&&this.ab()}Ca(){-1===this.N&&0<this.da.size&&(this.N=requestAnimationFrame(this.dc))}ab(){-1!==this.N&&(cancelAnimationFrame(this.N),this.N=-1)}Sb(){this.N=-1;for(const a of this.da)a();this.Ca()}Ba(){this.J.Ba()}Bb(){this.nb=!0}vb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}xb(a){return!this.vb(a)}async K(a){return"cordova"===
this.g&&(a.startsWith("file:")||this.Ia&&this.xb(a))?(a.startsWith(this.l)&&(a=a.substr(this.l.length)),a=await this.sa(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ob(a){const b=a.filename;switch(a.as){case "text":return await this.tb(b);case "buffer":return await this.sa(b);default:throw Error("unsupported type");}}Wa(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async tb(a){a=
await this.Wa(a);return await ja(a)}xa(){if(A.length&&!(8<=B)){B++;var a=A.shift();this.Fb(a.filename,a.nc,a.fc)}}sa(a){return new Promise((b,d)=>{A.push({filename:a,nc:e=>{B--;this.xa();b(e)},fc:e=>{B--;this.xa();d(e)}});this.xa()})}async Fb(a,b,d){try{const e=await this.Wa(a),f=await ka(e);b(f)}catch(e){d(e)}}gb(a){if("entered-fullscreen"===a)c.ma(!0),I(this.J);else if("exited-fullscreen"===a)c.ma(!1),I(this.J);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Ta(a),
this.Ta=null):"extension-message"===b?this.ia("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Vb(a){this.G({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}G(a){this.u()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Zb(){window.moveTo=(a,b)=>{this.G({type:"set-window-position",
windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=(a,b)=>{this.G({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Mb(){return this.u()?new Promise(a=>{this.Ta=a;this.G({type:"wrapper-init"})}):Promise.resolve()}async Eb(){const a=[];for(const [b,d]of Object.entries(this.B))a.push(this.Db(b,d));await Promise.all(a)}async Db(a,b){if("object"===typeof b)this.B[a]=new Blob([b.str],{type:b.type}),this.na[a]=b.str;else{let d=await this.Ib(b);d||(d=this.Gb(b));this.B[a]=
d}}async Ib(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}Gb(a){a=this.Xb(a);return this.Cb(a.data,a.jc)}Xb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===
b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{jc:a,data:d}}Cb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";
const J=self.C,ta=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},L={dispatchUserScriptEvent:!0},M={dispatchRuntimeEvent:!0};function va(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}function wa(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}
async function N(c){c=URL.createObjectURL(c);try{return await wa(c)}finally{URL.revokeObjectURL(c)}}function xa(c){return new Promise((a,b)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsText(c)})}
async function ya(c,a,b){if(!/firefox/i.test(navigator.userAgent))return await N(c);var d=await xa(c);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await N(c)}e.setAttribute("width",a+"px");e.setAttribute("height",b+"px");d=(new XMLSerializer).serializeToString(d);c=new Blob([d],{type:"image/svg+xml"});return await N(c)}
function P(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const za=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function Q(c){c.target.tagName&&Ba.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function R(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Ca(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await N(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ya(c,a,b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let S=!1;document.addEventListener("pause",()=>S=!0);document.addEventListener("resume",()=>S=!1);function G(c){c.addEventListener("selectstart",Q);c.addEventListener("gesturehold",Q);c.addEventListener("pointerdown",Q)}function H(c){c.addEventListener("selectstart",R);c.addEventListener("gesturehold",R);c.addEventListener("touchstart",R)}function ra(c){c.lb=!0;c.Ka=c.h.v();c.ba=c.h.o()}
function I(c){if(!c.s){var a=J.V();a&&"any"!==c.Ra&&Da(c);m(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.v(),innerHeight:c.o()})}}async function Ea(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Fa(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ga(c){return await self.C3_GetSvgImageSize(c.blob)}function Ha(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ia(c){self.setTimeout(()=>{c.kb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>T(c,!0)),document.addEventListener("resume",()=>T(c,!1))):document.addEventListener("visibilitychange",()=>T(c,"hidden"===document.visibilityState));c.oa=!("hidden"!==document.visibilityState&&!S);return{isSuspended:c.oa}}
function Ja(c){c.jb||(c.jb=!0,window.addEventListener("deviceorientation",a=>{c.s||m(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||m(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ka(c){c.ib||(c.ib=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function La(c){await va(c.url)}
function Ma(c,a){c.mb=a.message;-1===c.Fa&&(c.Fa=setTimeout(()=>{c.Fa=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.mb)},250))}function V(c,a){console.warn("[Construct] Fullscreen request failed: ",a);m(c,"fullscreenerror",{isFullscreen:J.V(),innerWidth:c.v(),innerHeight:c.o()})}
function T(c,a){c.oa!==a&&((c.oa=a)?c.h.ab():c.h.Ca(),m(c,"visibilitychange",{hidden:a}),!a&&c.h.W()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function Na(c,a,b){"Backspace"===b.key&&Q(b);if(c.h.u()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(b.key)||b.ctrlKey&&d.includes(b.key))&&b.preventDefault()}c.s||(d=ta.get(b.code)||b.code,r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},K))}
function W(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function X(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Na);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.F,pageX:b.pageX,pageY:b.pageY+c.F,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},K);"mouse"===b.pointerType&&(c.Na=
b.buttons)}}function Y(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.F=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.F=a))}}
function Oa(c,a,b,d){const e=c.v(),f=c.o();c.P=-1;e!=a||f!=b?m(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.V()}):10>d&&Pa(c,e,f,d+1)}function Pa(c,a,b,d){-1!==c.P&&clearTimeout(c.P);c.P=setTimeout(()=>Oa(c,a,b,d),48)}
function Da(c){c=c.Ra;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Qa(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
J.T(class extends self.U{constructor(c){super(c,"runtime");this.lb=!1;this.P=-1;this.Ra="any";this.oa=this.ib=this.jb=!1;this.pa=document.createElement("div");this.pa.className="c3-screen-reader-text";this.pa.setAttribute("aria-live","polite");document.body.appendChild(this.pa);this.H=null;this.s=!1;this.mb="";this.Fa=-1;this.kb=!1;this.Ka=c.v();this.ba=c.o();this.F=this.ea=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ea(b));c.i("runtime","raster-svg-image",b=>Fa(b));c.i("runtime","get-svg-image-size",b=>Ga(b));c.i("runtime","set-target-orientation",b=>{this.Ra=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Ha(b));c.i("runtime","go-to-script",b=>Ha(b));c.i("runtime","before-start-ticking",()=>Ia(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.H||(this.H=document.createElement("div"),this.H.id="inspectOutline",document.body.appendChild(this.H));var d=this.H;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.H&&(this.H.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ja(this));c.i("runtime","enable-device-motion",()=>Ka(this));c.i("runtime","add-stylesheet",b=>La(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>this.za(b));c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.pa.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+b.id))?
d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");this.h.ub().style.display=
"";this.h.Bb()});c.i("runtime","export-to-video-progress",b=>Ma(this,b));c.i("runtime","exported-to-video",b=>{window.ec({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.ec({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||P(d)||b.preventDefault()});
window.addEventListener("selectstart",Q);window.addEventListener("gesturehold",Q);window.addEventListener("touchstart",Q,{passive:!1});window.addEventListener("pointerdown",Q,{passive:!1});this.Na=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.lb){var b=this.v();var d=this.o();if(this.h.Ya()){if(this.kb){if(this.Ka===
b&&d<this.ba){this.ea=this.ba-d;Y(this,this.ba,this.ea);b=void 0;break a}0<this.ea&&(this.ea=0,Y(this,d,this.ea))}this.Ka=b;this.ba=d}m(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.V()});this.h.W()&&(-1!==this.P&&clearTimeout(this.P),Oa(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>I(this));
window.addEventListener("fullscreenerror",b=>V(this,b));window.addEventListener("webkitfullscreenerror",b=>V(this,b));window.addEventListener("mozfullscreenerror",b=>V(this,b));if(c.W()){if(window.visualViewport){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var b=e.tagName.toLowerCase();
var d=new Set("email number password search tel text url".split(" "));b="textarea"===b?!0:"input"===b?d.has(e.type.toLowerCase()||"text"):P(e)}else b=!1}b||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Ma=new Set;this.cc=new WeakSet;this.ac=!1}Va(){window.addEventListener("focus",()=>{m(this,"window-focus",null,M)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}m(this,"window-blur",
{parentHasFocus:a},M);this.Na=0});window.addEventListener("focusin",a=>{a=a.target;(za.has(a.tagName.toLowerCase())||P(a))&&m(this,"keyboard-blur",null,M)});window.addEventListener("keydown",a=>Na(this,"keydown",a));window.addEventListener("keyup",a=>Na(this,"keyup",a));window.addEventListener("mousedown",a=>W(this,"mousedown",a,L));window.addEventListener("mousemove",a=>W(this,"mousemove",a,L));window.addEventListener("mouseup",a=>W(this,"mouseup",a,L));window.addEventListener("dblclick",a=>W(this,
"dblclick",a,K));window.addEventListener("wheel",a=>{this.s||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.F,pageX:a.pageX,pageY:a.pageY+this.F,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Qa(a.target)&&document.activeElement&&!Qa(document.activeElement)&&document.activeElement.blur();X(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{X(this,"pointermove",a)}):window.addEventListener("pointermove",a=>X(this,"pointermove",a));window.addEventListener("pointerup",a=>X(this,"pointerup",a));window.addEventListener("pointercancel",a=>X(this,"pointercancel",a));const c=()=>this.Ba();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",
c,!0);this.h.wb()&&!this.h.Ya()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.W()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}v(){return this.h.v()}o(){return this.h.o()}Ba(){var c=[...this.Ma];this.Ma.clear();if(!this.ac)for(const a of c)(c=a.play())&&c.catch(()=>{this.cc.has(a)||this.Ma.add(a)})}za(c){alert(c.message)}});
"use strict";async function pa(c){if(c.$b)throw Error("already initialised");c.$b=!0;var a=c.D.ya(("playable-ad"===c.D.g?c.D.O:"")+"dispatchworker.js");c.Ea=await c.D.ta(a,c.X,{name:"DispatchWorker"});a=new MessageChannel;c.Ha=a.port1;c.Ea.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Oa=await sa(c)}function qa(c){return[c.Ha,c.Oa]}
async function sa(c){const a=c.pb.length;var b=c.D.ya(("playable-ad"===c.D.g?c.D.O:"")+"jobworker.js");b=await c.D.ta(b,c.X,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.Ea.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.pb.push(b);return e.port1}
self.zb=class{constructor(c){this.D=c;this.X=c.l;this.X="preview"===c.g?this.X+"workers/":this.X+c.O;this.bc=Math.min(navigator.hardwareConcurrency||2,16);this.Ea=null;this.pb=[];this.Oa=this.Ha=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.C({oc:!0,pc:"workermain.js",S:["scripts/c3runtime.js"],qa:[],Ua:"",lc:"scripts/",ra:["csv-parse-sync.js","csv-stringify-sync.js"],sb:"html5"}));"use strict";
async function Ra(c,a){a=a.type;let b=!0;0===a?b=await Sa():1===a&&(b=await Ta());m(c,"permission-result",{type:a,result:b})}async function Sa(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}
async function Ta(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}self.C.T(class extends self.U{constructor(c){super(c,"touch");t(this,"request-permission",a=>Ra(this,a))}});"use strict";
async function Ua(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(c){return console.error("[Construct] Error requesting persistent storage: ",c),{isOk:!1}}}self.C.T(class extends self.U{constructor(c){super(c,"localstorage");u(this,[["init",()=>this.ja()],["request-persistent",()=>Ua()]])}async ja(){let c=!1;try{c=await navigator.storage.persisted()}catch(a){c=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:c}}});"use strict";
function Va(){}function Wa(c){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(c,"sw-message",a.data))}
function Xa(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.C.T(class extends self.U{constructor(c){super(c,"browser");this.g="";u(this,[["get-initial-state",a=>{this.g=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Wa(this)],
["alert",a=>this.za(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Aa(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Xa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===
a||this.h.u()?window.open(b,"_blank"):this.uc||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if(this.h.u()||"macos-wkwebview"===this.g)self.C.ma(!0),this.h.G({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");
a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(b):a.mozRequestFullScreen?d=a.mozRequestFullScreen(b):a.msRequestFullscreen?d=a.msRequestFullscreen(b):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Va)}}],["exit-fullscreen",()=>{if(this.h.u()||"macos-wkwebview"===this.g)self.C.ma(!1),this.h.G({type:"set-fullscreen",fullscreen:!1});
else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Va)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const b=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var h=document.querySelector(e);
f=h?[h]:[]}else f=[document.documentElement];e=f;for(const g of e)b.startsWith("--")?g.style.setProperty(b,d):g.style[b]=d}catch(g){console.warn("[Browser] Failed to set style: ",g)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var b=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),b={isOk:!1}}}return b}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],
["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}za(c){alert(c.message)}Aa(c){c=c.isFocus;if("nwjs"===this.g){const a="nwjs"===this.g?nw.Window.get():null;c?a.focus():
a.blur()}else c?window.focus():window.blur()}});"use strict";function Z(c){c.stopPropagation()}function Ya(c){13!==c.which&&27!==c.which&&c.stopPropagation()}
self.C.T(class extends self.ua{constructor(c){super(c);ca(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}Xa(c,a){let b;const d=a.type;"textarea"===d?(b=document.createElement("textarea"),b.style.resize="none"):(b=document.createElement("input"),b.type=d);b.style.position="absolute";b.autocomplete="off";b.addEventListener("pointerdown",Z);b.addEventListener("pointermove",Z);b.addEventListener("pointerrawupdate",Z);b.addEventListener("pointerup",Z);b.addEventListener("mousedown",Z);b.addEventListener("mouseup",
Z);b.addEventListener("keydown",Ya);b.addEventListener("keyup",Ya);b.addEventListener("click",e=>{e.stopPropagation();da(this,"click",c)});b.addEventListener("dblclick",e=>{e.stopPropagation();da(this,"dblclick",c)});b.addEventListener("input",()=>v(this,"change",c,{text:b.value}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.wa(b,a);return b}wa(c,a){c.value=a.text;c.placeholder=a.placeholder;c.title=a.title;c.disabled=!a.isEnabled;c.readOnly=a.isReadOnly;c.spellcheck=a.spellCheck;
a=a.maxLength;0>a?c.removeAttribute("maxlength"):c.setAttribute("maxlength",a)}});
